services:
  # 1. POSTGRES (Metadata Store)
  postgres:
    image: postgres:15
    container_name: stream_rec_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MINIO (S3 Storage)
  minio:
    image: minio/minio
    container_name: stream_rec_minio
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # 3. REDIS (Feature Store - Online)
  redis:
    image: redis:alpine
    container_name: stream_rec_redis
    ports:
      - "6399:6379"
    volumes:
      - redis_data:/data

  # 4. MLFLOW (Model Registry)
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: stream_rec_mlflow
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_S3_IGNORE_TLS: "true"
    depends_on:
      - postgres
      - minio
    command: >
      sh -c "pip install psycopg2-binary boto3 && mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      --default-artifact-root s3://${MINIO_BUCKET_NAME}/ 
      --host 0.0.0.0"

  # # 5. MAGE (Orchestrator)
  # mage:
  #   image: mageai/mageai:latest
  #   container_name: stream_rec_mage
  #   ports:
  #     - "6789:6789"
  #   volumes:
  #     - .:/home/src
  #   environment:
  #     USER_CODE_PATH: /home/src
  #     PROJECT_NAME: my_mlops_project

  # 6. INFERENCE API
  inference_api:
    build:
      context: ./services/inference_api
      dockerfile: Dockerfile
    container_name: stream_rec_inference_api
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-1
      AWS_S3_ADDRESSING_STYLE: path
      MLFLOW_S3_IGNORE_TLS: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mlflow
      - minio
      - redis
    volumes:
      - ./feature_repo:/app/feature_repo
      - ./training:/app/training

  # 7. STREAM PROCESSOR
  stream_processor:
    build:
      context: ./services/stream_processor
      dockerfile: Dockerfile
    container_name: stream_rec_stream_processor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redpanda
      - redis
    volumes:
      - ./feature_repo:/app/feature_repo

  # 8. EVENT SIMULATOR
  event_simulator:
    build:
      context: ./services/event_simulator
      dockerfile: Dockerfile
    container_name: stream_rec_event_simulator
    depends_on:
      - redpanda

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.11
    container_name: stream_rec_redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"

  prometheus:
    image: prom/prometheus:latest
    container_name: stream_rec_prometheus
    volumes:
      # Mount the config file we just created into the container
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: stream_rec_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  postgres_data:
  minio_data:
  redis_data: